# The name of your Pages project, required for `wrangler pages deploy`
# You should change this to the name of your project on Cloudflare
name = "egs-pillay-group"

# The compatibility date specifies the version of the Cloudflare Workers runtime.
# Using a recent date is recommended.
compatibility_date = "2024-05-02"

# This flag is essential for Next.js applications on Cloudflare Pages.
# It enables compatibility with Node.js APIs that Next.js depends on.
compatibility_flags = [ "nodejs_compat" ]
